apiVersion: v1
kind: Pod
metadata:
  name: test-pod-secret 
spec:
  containers:
  - name: test-secret-volume
    image: busybox
    args:
    - sleep
    - "86400"
    volumeMounts:
    - name: mysecret
      mountPath: "/mysecret"
      readOnly: true
  volumes:
  - name: mysecret
    secret:
      secretName: mysecret
    